//remaining + amount == amount in quests{xx:amount}, xx:amount}, xx:amount}
    //amount = osszes
    //remainig hatra van0, gyakorlatilag == (handedin + ininventory) - amount
//remaining: 0,  amount : 0, quests : {questIdFromQuest.js : questAmount, questIdFromQuest.js : questAmount,},
let items = {
'3-b-TG':{crafted : false,  barter : false,  handedin: 0, ininventory: 0, remaining: 0,  amount : 0, quests : {}, inraid : true},
'OFZ 160mm Shell':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining: 5, amount : 5, quests : {26:5}, inraid : true},
'303 Dorm Room Key':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'42nd Signature Blend English Tea':{crafted : false,  barter : false,  handedin : 0, ininventory: 0,remaining:0, amount : 0, quests : {}, inraid : true},
'5L propane tank':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'60-round mags for AK':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {9:3}, inraid : true},
'6B43 greater than 50 percent':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'6B43 less than 50 percent':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'7 PMC BEAR dogtags':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:7, amount : 7, quests : {19:7}, inraid : true},
'7 USEC BEAR dogtags':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:7, amount : 7, quests : {19:7}, inraid : true},
'AHF1-M':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Alkali':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Antique Teapots':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Antique Vases':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Antique axe':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Aramid Fiber Cloth':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'BNTI Gzhel-K armor':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Bars A-2607':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:5, amount : 5, quests : {17:5}, inraid : true},
'Battered Antique Book':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'BlackRock Chest Rig':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Blue Keycard':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Broken GPhone':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Bronze Lion':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'CMS surgery kits':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'CPU':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Can of Dr Lupos coffee beans':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Can of sprats':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Capacitors':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Car Batteries':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Cat figurine':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Clin wipers':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Corrugated hoses':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Cowboy Hat':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Customs Military Checkpoint key':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Deadlyslobs beard oil':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Delicious Beef Stew':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Dollars':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Emelya Rye Croutons':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Euro':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Fake Mustache':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'FireKlean Gun Lube':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Fleece Cloth':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Fuel Conditioner':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Gas Station Closet Key':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Gas analyzer':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Gold Chains':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Golden 1GPhone':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Golden Rooster':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Golden TT':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Goshan Cash Register Key':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Graphics Card':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Green Keycard':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Gunpowder - Kite':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Gzhel greater than 50 percent':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Gzhel less than 50 percent':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Horse Figurine':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Informant\'s Briefcase':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Iskra lunch boxes':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Jar of DevilDog Mayo':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'KEKTAPE Duct Tape':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Killas helmet':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Kotton Beanie':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'LEDX':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'M4A1':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {18:1}, inraid : true},
'M67 grenades':{crafted : false,  barter : true,  handedin : 0, ininventory: 0, remaining:10, amount : 10, quests : {28:10}, inraid : false},
'MP-133 pump-action shotguns':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {0:2}, inraid: false },
'MRE ration packs':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Malboro cigarettes':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Medical bloodset':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Military COFDM wireless Signal Transmitter':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'6 STEN 140 Military battery':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {26:1}, inraid : true},
'Module 3M BodyArmor':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Morphine Syringes':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Multitool':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Old Firesteel':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Ophthalmoscope':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Ox Bleach':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'PM pistol':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Paracord':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Pestily Plague Mask':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Pilgrim Tourist Backpack':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Polyamide Fabric':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Portable Defibrillator':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Powercord':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Printed circuit board':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Raven Figurine':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Rechargeable battery':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Respirator':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Ripstop Cloth':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Roler Submariner Gold Wrist Watch':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Roler watch':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Roubles':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Salewa kits':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Sanitar Stimulants all':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Sanitars ophtalmoscope':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Sanitars surgery kit':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Shroud Half-mask':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Shturmans key':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Silver Badge':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Ski Hat With Holes for Eyes':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Sniper Rifle SV-98':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'Spark Plugs':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Strike cigarettes':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'T-Shaped Plug':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'TOZ 106':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'TerraGroup Labs access keycards':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'The key from the locked resort rooms':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Tushonka':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'UHF RFID Reader':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'USB flash drives':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Ushanka Ear-flap Cap':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'VPX Flash Storage Module':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Veritas Guitar Pick':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Virtex programmable processors':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'WD-40 100ml':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Wartech TV-109' :{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Wilston cigarettes':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'Wires':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : true},
'ZB-014 key':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:0, amount : 0, quests : {}, inraid : false},
'AK-74N assault rifle':{crafted : true,  barter : false,  handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {18:1}, inraid : true},
'Lower half-mask':{crafted : false,  barter : false,  handedin : 0, ininventory: 0, remaining:7, amount : 7, quests : {15:7}, inraid : true},
};

let options = {
'show_quests' : true,
'show_collector' : true,
'show_0_remaining' : true,
};
