let items = {
'3-b-TG':{crafted : false, barter : false, handedin: 0, ininventory: 0, remaining: 1,  amount : 1, quests : {49:1}, inraid : true},
'30-mil shells for BMP cannon':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining: 5, amount : 5, quests : {24:5}, inraid : true},
'303 Dorm Room Key':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {52:1}, inraid : false},
'42nd Signature Blend English Tea':{crafted : false, barter : false, handedin : 0, ininventory: 0,remaining:1, amount : 1, quests : {201:1}, inraid : true},
'5L propane tank':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {89:2}, inraid : true},
'60-round mags for AK':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {9:3}, inraid : true},
'6B43 less than 50 percent':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {159:1}, inraid : false},
'6B43 greater than 50 percent':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {159:1}, inraid : false},
'7 PMC BEAR dogtags':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:7, amount : 7, quests : {17:7}, inraid : false},
'7 USEC BEAR dogtags':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:7, amount : 7, quests : {17:7}, inraid : false},
'AHF1-M':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {49:1}, inraid : true},
'Alkali':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {89:2}, inraid : true},
'Antique axe':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Antique Teapots':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {153:3}, inraid : true},
'Antique Vases':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {153:2}, inraid : true},
'Aramid Fiber Cloth':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:5, amount : 5, quests : {163:5}, inraid : true},
'Bars A-2607':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:5, amount : 5, quests : {15:5}, inraid : true},
'Battered Antique Book':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'BlackRock Chest Rig':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {161:2}, inraid : true},
'Blue Keycard':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {49:1}, inraid : false},
'BNTI Gzhel-K armor':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {144:2}, inraid : false},
'Broken GPhone':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {124:3}, inraid : true},
'Bronze Lion':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {160:2}, inraid : true},
'Can of Dr Lupos coffee beans':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Can of sprats':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Capacitors':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:5, amount : 5, quests : {135:5}, inraid : true},
'Car Batteries':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:4, amount : 4, quests : {34:4}, inraid : true},
'Cat figurine':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {160:1}, inraid : true},
'Clin wipers':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {85:2}, inraid : true},
'CMS surgery kits':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {177:2}, inraid : true},
'Corrugated hoses':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:4, amount : 4, quests : {85:2,89:2}, inraid : true},
'Cowboy Hat':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {142:2}, inraid : true},
'CPU':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {124:3}, inraid : true},
'Customs Military Checkpoint key':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {52:1}, inraid : false},
'Deadlyslobs beard oil':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Delicious Beef Stew':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {165:2}, inraid : true},
'Dollars':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:14500, amount : 14500, quests : {35:500,66:6000,87:8000}, inraid : false},
'Emelya Rye Croutons':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {165:2}, inraid : true},
'Euro':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:50000, amount : 50000, quests : {99:50000}, inraid : false},
'Fake Mustache':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'FireKlean Gun Lube':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Fleece Cloth':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:10, amount : 10, quests : {164:10}, inraid : true},
'Fuel Conditioner':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:4, amount : 4, quests : {151:4}, inraid : true},
'Gas analyzer':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {30:1, 31:2}, inraid : true},
'Gas Station Closet Key':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {52:1}, inraid : false},
'Gold Chains':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:9, amount : 9, quests : {68:9}, inraid : false},
'Golden 1GPhone':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Golden Rooster':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Golden TT':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {184:1}, inraid : true},
'Goshan Cash Register Key':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {158:1}, inraid : false},
'Green Keycard':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {49:1}, inraid : false},
'Graphics Card':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {132:3}, inraid : false},
'Gunpowder - Kite':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {44:3}, inraid : false},
'Gzhel less than 50 percent':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {154:1}, inraid : false},
'Gzhel greater than 50 percent':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {154:1}, inraid : false},
'Horse Figurine':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {160:2}, inraid : true},
'Iskra lunch boxes':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {165:3}, inraid : true},
'Jar of DevilDog Mayo':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'KEKTAPE Duct Tape':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:5, amount : 5, quests : {164:5}, inraid : true},
'Killas helmet':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {186:1}, inraid : true},
'Kotton Beanie':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'LEDX':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {43:1}, inraid : true},
'M4A1':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {16:1}, inraid : true},
'M67 grenades':{crafted : false, barter : true, handedin : 0, ininventory: 0, remaining:10, amount : 10, quests : {26:10}, inraid : false},
'Malboro cigarettes':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:5, amount : 5, quests : {130:5}, inraid : true},
'Medical bloodset':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {64:3}, inraid : true},
'Military battery':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {24:1}, inraid : true},
'Military COFDM wireless Signal Transmitter':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {103:1}, inraid : true},
'Module 3M BodyArmor':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {53:1}, inraid : true},
'Morphine Syringes':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:8, amount : 8, quests : {32:4,89:4}, inraid : true},
'MP-133 pump-action shotguns':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {0:2}, inraid: true },
'MRE ration packs':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:4, amount : 4, quests : {80:4}, inraid : false},
'Multitool':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {76:1}, inraid : false},
'Old Firesteel':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Ophthalmoscope':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {43:2}, inraid : true},
'Ox Bleach':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {85:2}, inraid : true},
'Paracord':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {163:3}, inraid : true},
'Pestily Plague Mask':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Pilgrim Tourist Backpack':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {150:1}, inraid : true},
'PM pistol':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {16:2}, inraid : true},
'Polyamide Fabric':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:10, amount : 10, quests : {164:10}, inraid : true},
'Portable Defibrillator':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {177:2}, inraid : true},
'Powercord':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {129:2}, inraid : true},
'Printed circuit board':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:5, amount : 5, quests : {124:3,129:2}, inraid : true},
'Raven Figurine':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Rechargeable battery':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {124:3}, inraid : true},
'Respirator':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:4, amount : 4, quests : {64:4}, inraid : true},
'Ripstop Cloth':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:10, amount : 10, quests : {163:10}, inraid : true},
'Roler Submariner Gold Wrist Watch':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {160:1}, inraid : true},
'Roler watch':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {70:1}, inraid : false},
'Roubles':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1400000, amount : 1400000, quests : {40:400000,62:1000000}, inraid : false},
'Salewa kits':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:3, amount : 3, quests : {27:3}, inraid : true},
'Sanitar Stimulants all':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {101:1}, inraid : true},
'Sanitars ophtalmoscope':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {48:1}, inraid : true},
'Sanitars surgery kit':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {48:1}, inraid : true},
'Shroud Half-mask':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Shturmans key':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {187:1}, inraid : true},
'Silver Badge':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Ski Hat With Holes for Eyes':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {150:1}, inraid : true},
'Sniper Rifle SV-98':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {70:1,76:1}, inraid : false},
'Spark Plugs':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:8, amount : 8, quests : {34:8}, inraid : true},
'Strike cigarettes':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:5, amount : 5, quests : {130:5}, inraid : true},
'T-Shaped Plug':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:4, amount : 4, quests : {129:4}, inraid : true},
'TerraGroup Labs access keycards':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {183:2}, inraid : true},
'Tushonka':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:15, amount : 15, quests : {46:15}, inraid : true},
'The key from the locked resort rooms':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {87:1}, inraid : true},
'TOZ 106':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {53:1}, inraid : true},
'UHF RFID Reader':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {136:1}, inraid : true},
'USB flash drives':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:5, amount : 5, quests : {56:2,199:3}, inraid : true},
'Ushanka Ear-flap Cap':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {142:2}, inraid : true},
'Veritas Guitar Pick':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {201:1}, inraid : true},
'Virtex programmable processors':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {103:1}, inraid : true},
'VPX Flash Storage Module':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {136:1}, inraid : true},
'Wartech TV-109' :{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:2, amount : 2, quests : {161:2}, inraid : true},
'WD-40 100ml':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {85:1}, inraid : true},
'Wilston cigarettes':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:5, amount : 5, quests : {130:5}, inraid : true},
'Wires':{crafted : true, barter : false, handedin : 0, ininventory: 0, remaining:5, amount : 5, quests : {135:5}, inraid : true},
'ZB-014 key':{crafted : false, barter : false, handedin : 0, ininventory: 0, remaining:1, amount : 1, quests : {52:1}, inraid : false}};

let options = {
'show_quests' : true,
'show_collector' : true,
'show_0_remaining' : true,
};
