//file edited by hand
let isBarterisCraft = {
  "3-(b-TG) stimulant injector":{inraid: 0, barter : 0, craft : 0},
  "42nd Signature Blend English Tea":{inraid: 0, barter : 0, craft : 0},
  "5L propane tanks":{inraid: 0, barter : 0, craft : 0},
  "6-STEN-140-M military battery":{inraid: 0, barter : 0, craft : 0},
  "6B43 armor in 0-50% condition":{inraid: 0, barter : 0, craft : 0},
  "6B43 armor in 50-100% condition":{inraid: 0, barter : 0, craft : 0},
  "AHF1-M stimulant injector":{inraid: 0, barter : 0, craft : 0},
  "AK-74 5.45x39 6L31 60-round magazine":{inraid: 0, barter : 0, craft : 0},
  "AK-74N assault rifle":{inraid: 0, barter : 0, craft : 0},
  "Alkaline cleaners for heat exchangers":{inraid: 0, barter : 0, craft : 0},
  "Antique axe":{inraid: 0, barter : 0, craft : 0},
  "Antique teapots":{inraid: 0, barter : 0, craft : 0},
  "Antique vases":{inraid: 0, barter : 0, craft : 0},
  "Aramid fabrics":{inraid: 0, barter : 0, craft : 0},
  "BEAR PMC dogtags":{inraid: 0, barter : 0, craft : 0},
  "BNTI Gzhel-K armor in 0-50% durability":{inraid: 0, barter : 0, craft : 0},
  "BNTI Gzhel-K armor in 50-100% durability":{inraid: 0, barter : 0, craft : 0},
  "BOSS cap":{inraid: 0, barter : 0, craft : 0},
  "Bars A-2607 knives":{inraid: 0, barter : 0, craft : 0},
  "Battered antique book":{inraid: 0, barter : 0, craft : 0},
  "BlackRock chest rigs":{inraid: 0, barter : 0, craft : 0},
  "Bottles of Dan Jackiel whiskey":{inraid: 0, barter : 0, craft : 0},
  "Bottles of Tarkovskaya vodka":{inraid: 0, barter : 0, craft : 0},
  "Broken GPhones":{inraid: 0, barter : 0, craft : 0},
  "CMS surgery kits":{inraid: 0, barter : 0, craft : 0},
  "CPU Fans":{inraid: 0, barter : 0, craft : 0},
  "Can of Dr. Lupo's coffee beans":{inraid: 0, barter : 0, craft : 0},
  "Can of RatCola":{inraid: 0, barter : 0, craft : 0},
  "Can of sprats":{inraid: 0, barter : 0, craft : 0},
  "Capacitors":{inraid: 0, barter : 0, craft : 0},
  "Car batteries":{inraid: 0, barter : 0, craft : 0},
  "Cat figurine":{inraid: 0, barter : 0, craft : 0},
  "Clin window cleaners":{inraid: 0, barter : 0, craft : 0},
  "Cordura polyamide fabrics":{inraid: 0, barter : 0, craft : 0},
  "Corrugated hoses":{inraid: 0, barter : 0, craft : 0},
  "Customs military checkpoint key":{inraid: 0, barter : 0, craft : 0},
  "Deadlyslob's beard oil":{inraid: 0, barter : 0, craft : 0},
  "Dorm room 303 key":{inraid: 0, barter : 0, craft : 0},
  "EUR":{inraid: 0, barter : 0, craft : 0},
  "Evasion armband":{inraid: 0, barter : 0, craft : 0},
  "Fake mustache":{inraid: 0, barter : 0, craft : 0},
  "FireKlean gun lube":{inraid: 0, barter : 0, craft : 0},
  "Fleece fabrics":{inraid: 0, barter : 0, craft : 0},
  "Fuel conditioners":{inraid: 0, barter : 0, craft : 0},
  "Gas analyzer":{inraid: 0, barter : 0, craft : 0},
  "Gas analyzers":{inraid: 0, barter : 0, craft : 0},
  "Gas station closet key":{inraid: 0, barter : 0, craft : 0},
  "Golden 1GPhone":{inraid: 0, barter : 0, craft : 0},
  "Golden rooster":{inraid: 0, barter : 0, craft : 0},
  "Graphics cards":{inraid: 0, barter : 0, craft : 0},
  "Horse figurines":{inraid: 0, barter : 0, craft : 0},
  "Jar of DevilDog mayo":{inraid: 0, barter : 0, craft : 0},
  "KEKTAPE duct tapes":{inraid: 0, barter : 0, craft : 0},
  "Killa's helmet":{inraid: 0, barter : 0, craft : 0},
  "Kinda Cowboy hats":{inraid: 0, barter : 0, craft : 0},
  "Kotton beanie":{inraid: 0, barter : 0, craft : 0},
  "L1 (Norepinephrine) stimulant injector":{inraid: 0, barter : 0, craft : 0},
  "LEDX Skin Transilluminator":{inraid: 0, barter : 0, craft : 0},
  "LVNDMARK's rat poison":{inraid: 0, barter : 0, craft : 0},
  "Loot Lord plushie":{inraid: 0, barter : 0, craft : 0},
  "Lower half-masks":{inraid: 0, barter : 0, craft : 0},
  "M.U.L.E. stimulant injector":{inraid: 0, barter : 0, craft : 0},
  "M4A1 assault rifle":{inraid: 0, barter : 0, craft : 0},
  "M67 grenades":{inraid: 0, barter : 0, craft : 0},
  "MP-133 shotguns":{inraid: 0, barter : 0, craft : 0}},
  "MRE ration packs":{inraid: 0, barter : 0, craft : 0},
  "Malboro cigarettes":{inraid: 0, barter : 0, craft : 0},
  "Medical bloodsets":{inraid: 0, barter : 0, craft : 0},
  "Meldonin stimulant injector":{inraid: 0, barter : 0, craft : 0},
  "Military COFDM wireless Signal Transmitter":{inraid: 0, barter : 0, craft : 0},
  "Military COFDM wireless Signal Transmitters":{inraid: 0, barter : 0, craft : 0},
  "Morphine injectors":{inraid: 0, barter : 0, craft : 0},
  "OFZ 30x160mm shells":{inraid: 0, barter : 0, craft : 0},
  "Old firesteel":{inraid: 0, barter : 0, craft : 0},
  "Ophthalmoscope":{inraid: 0, barter : 0, craft : 0},
  "Ox bleaches":{inraid: 0, barter : 0, craft : 0},
  "P22 stimulant injector":{inraid: 0, barter : 0, craft : 0},
  "PC CPUs":{inraid: 0, barter : 0, craft : 0},
  "PM 9x18PM pistols":{inraid: 0, barter : 0, craft : 0},
  "Paracords":{inraid: 0, barter : 0, craft : 0},
  "Pestily plague mask":{inraid: 0, barter : 0, craft : 0},
  "Pilgrim tourist backpack":{inraid: 0, barter : 0, craft : 0},
  "Portable defibrillator":{inraid: 0, barter : 0, craft : 0},
  "Power cords":{inraid: 0, barter : 0, craft : 0},
  "Printed circuit boards":{inraid: 0, barter : 0, craft : 0},
  "RUB":{inraid: 0, barter : 0, craft : 0},
  "Raven figurine":{inraid: 0, barter : 0, craft : 0},
  "Rechargeable batteries":{inraid: 0, barter : 0, craft : 0},
  "Reshala's Golden TT":{inraid: 0, barter : 0, craft : 0},
  "Respirators":{inraid: 0, barter : 0, craft : 0},
  "Ripstop fabrics":{inraid: 0, barter : 0, craft : 0},
  "Roler Submariner gold wrist watch":{inraid: 0, barter : 0, craft : 0},
  "Salewa first aid kits":{inraid: 0, barter : 0, craft : 0},
  "Secure Flash drives":{inraid: 0, barter : 0, craft : 0},
  "Secure container Epsilon":{inraid: 0, barter : 0, craft : 0},
  "Secure flash drives":{inraid: 0, barter : 0, craft : 0},
  "Shroud half-mask":{inraid: 0, barter : 0, craft : 0},
  "Shturman's stash key":{inraid: 0, barter : 0, craft : 0},
  "Silver Badge":{inraid: 0, barter : 0, craft : 0},
  "Ski hat with holes for eyes":{inraid: 0, barter : 0, craft : 0},
  "Small cans of beef stew":{inraid: 0, barter : 0, craft : 0},
  "Smoke balaclava":{inraid: 0, barter : 0, craft : 0},
  "Spark plugs":{inraid: 0, barter : 0, craft : 0},
  "Strike cigarettes":{inraid: 0, barter : 0, craft : 0},
  "T-Shaped Plugs":{inraid: 0, barter : 0, craft : 0},
  "TerraGroup Labs access keycards":{inraid: 0, barter : 0, craft : 0},
  "TerraGroup Labs keycard (Blue)":{inraid: 0, barter : 0, craft : 0},
  "TerraGroup Labs keycard (Green)":{inraid: 0, barter : 0, craft : 0},
  "UHF RFID Fixed Reader":{inraid: 0, barter : 0, craft : 0},
  "UHF RFID Readers":{inraid: 0, barter : 0, craft : 0},
  "USD":{inraid: 0, barter : 0, craft : 0},
  "USEC PMC dogtags":{inraid: 0, barter : 0, craft : 0},
  "Ushanka ear-flap caps":{inraid: 0, barter : 0, craft : 0},
  "VPX Flash Storage Module":{inraid: 0, barter : 0, craft : 0},
  "VPX Flash Storage Modules":{inraid: 0, barter : 0, craft : 0},
  "Veritas guitar pick":{inraid: 0, barter : 0, craft : 0},
  "Virtex programmable processors":{inraid: 0, barter : 0, craft : 0},
  "WARTECH TV-109 + TV-106 gear rigs":{inraid: 0, barter : 0, craft : 0},
  "WD-40 (100ml)":{inraid: 0, barter : 0, craft : 0},
  "WZ Wallet":{inraid: 0, barter : 0, craft : 0},
  "Wilston cigarettes":{inraid: 0, barter : 0, craft : 0},
  "Wires":{inraid: 0, barter : 0, craft : 0},
  "ZB-014 key":{inraid: 0, barter : 0, craft : 0},
  "\"Obdolbos\" cocktail injector":{inraid: 0, barter : 0, craft : 0},
  "found in raid Module-3M armor":{inraid: 0, barter : 0, craft : 0},
  "found in raid TOZ-106 shotgun":{inraid: 0, barter : 0, craft : 0},
  "knives":{inraid: 0, barter : 0, craft : 0},
  "purified water":{inraid: 0, barter : 0, craft : 0},
};
