//file edited by hand
let isBarterisCraft = {
    {"MP-133 shotguns": barter : 0, craft : 0},
    {"AK-74 5.45x39 6L31 60-round magazine": barter : 0, craft : 0},
    {"Lower half-masks": barter : 0, craft : 0},
    {"Bars A-2607 knives": barter : 0, craft : 0},
    {"AK-74N assault rifle": barter : 0, craft : 0},
    {"M4A1 assault rifle": barter : 0, craft : 0},
    {"PM 9x18PM pistols": barter : 0, craft : 0},
    {"BEAR PMC dogtags": barter : 0, craft : 0},
    {"USEC PMC dogtags": barter : 0, craft : 0},
    {"6-STEN-140-M military battery": barter : 0, craft : 0},
    {"OFZ 30x160mm shells": barter : 0, craft : 0},
    {"M67 grenades": barter : 0, craft : 0},
    {"Salewa first aid kits": barter : 0, craft : 0},
    {"Gas analyzer": barter : 0, craft : 0},
    {"Gas analyzers": barter : 0, craft : 0},
    {"Morphine injectors": barter : 0, craft : 0},
    {"Car batteries": barter : 0, craft : 0},
    {"Spark plugs": barter : 0, craft : 0},
    {"USD": barter : 0, craft : 0},
    {"RUB": barter : 0, craft : 0},
    {"Ophthalmoscope": barter : 0, craft : 0},
    {"LEDX Skin Transilluminator": barter : 0, craft : 0},
    {"Small cans of beef stew": barter : 0, craft : 0},
    {"TerraGroup Labs keycard (Blue)": barter : 0, craft : 0},
    {"TerraGroup Labs keycard (Green)": barter : 0, craft : 0},
    {"AHF1-M stimulant injector": barter : 0, craft : 0},
    {"3-(b-TG) stimulant injector": barter : 0, craft : 0},
    {"Dorm room 303 key": barter : 0, craft : 0},
    {"ZB-014 key": barter : 0, craft : 0},
    {"Customs military checkpoint key": barter : 0, craft : 0},
    {"Gas station closet key": barter : 0, craft : 0},
    {"found in raid Module-3M armor": barter : 0, craft : 0},
    {"found in raid TOZ-106 shotgun": barter : 0, craft : 0},
    {"Secure flash drives": barter : 0, craft : 0},
    {"Respirators": barter : 0, craft : 0},
    {"Medical bloodsets": barter : 0, craft : 0},
    {"knives": barter : 0, craft : 0},
    {"MRE ration packs": barter : 0, craft : 0},
    {"WD-40 (100ml)": barter : 0, craft : 0},
    {"Clin window cleaners": barter : 0, craft : 0},
    {"Corrugated hoses": barter : 0, craft : 0},
    {"Ox bleaches": barter : 0, craft : 0},
    {"Alkaline cleaners for heat exchangers": barter : 0, craft : 0},
    {"5L propane tanks": barter : 0, craft : 0},
    {"EUR": barter : 0, craft : 0},
    {"M.U.L.E. stimulant injector": barter : 0, craft : 0},
    {"\"Obdolbos\" cocktail injector": barter : 0, craft : 0},
    {"Meldonin stimulant injector": barter : 0, craft : 0},
    {"P22 stimulant injector": barter : 0, craft : 0},
    {"L1 (Norepinephrine) stimulant injector": barter : 0, craft : 0},
    {"Virtex programmable processors": barter : 0, craft : 0},
    {"Military COFDM wireless Signal Transmitter": barter : 0, craft : 0},
    {"VPX Flash Storage Modules": barter : 0, craft : 0},
    {"UHF RFID Readers": barter : 0, craft : 0},
    {"Military COFDM wireless Signal Transmitters": barter : 0, craft : 0},
    {"PC CPUs": barter : 0, craft : 0},
    {"Rechargeable batteries": barter : 0, craft : 0},
    {"Printed circuit boards": barter : 0, craft : 0},
    {"Broken GPhones": barter : 0, craft : 0},
    {"Power cords": barter : 0, craft : 0},
    {"T-Shaped Plugs": barter : 0, craft : 0},
    {"Malboro cigarettes": barter : 0, craft : 0},
    {"Strike cigarettes": barter : 0, craft : 0},
    {"Wilston cigarettes": barter : 0, craft : 0},
    {"Graphics cards": barter : 0, craft : 0},
    {"CPU Fans": barter : 0, craft : 0},
    {"Wires": barter : 0, craft : 0},
    {"Capacitors": barter : 0, craft : 0},
    {"UHF RFID Fixed Reader": barter : 0, craft : 0},
    {"VPX Flash Storage Module": barter : 0, craft : 0},
    {"Ushanka ear-flap caps": barter : 0, craft : 0},
    {"Kinda Cowboy hats": barter : 0, craft : 0},
    {"Ski hat with holes for eyes": barter : 0, craft : 0},
    {"Pilgrim tourist backpack": barter : 0, craft : 0},
    {"Fuel conditioners": barter : 0, craft : 0},
    {"Antique teapots": barter : 0, craft : 0},
    {"Antique vases": barter : 0, craft : 0},
    {"BNTI Gzhel-K armor in 0-50% durability": barter : 0, craft : 0},
    {"BNTI Gzhel-K armor in 50-100% durability": barter : 0, craft : 0},
    {"6B43 armor in 0-50% condition": barter : 0, craft : 0},
    {"6B43 armor in 50-100% condition": barter : 0, craft : 0},
    {"Horse figurines": barter : 0, craft : 0},
    {"Cat figurine": barter : 0, craft : 0},
    {"Roler Submariner gold wrist watch": barter : 0, craft : 0},
    {"WARTECH TV-109 + TV-106 gear rigs": barter : 0, craft : 0},
    {"BlackRock chest rigs": barter : 0, craft : 0},
    {"Aramid fabrics": barter : 0, craft : 0},
    {"Ripstop fabrics": barter : 0, craft : 0},
    {"Paracords": barter : 0, craft : 0},
    {"Fleece fabrics": barter : 0, craft : 0},
    {"Cordura polyamide fabrics": barter : 0, craft : 0},
    {"KEKTAPE duct tapes": barter : 0, craft : 0},
    {"Bottles of Tarkovskaya vodka": barter : 0, craft : 0},
    {"Bottles of Dan Jackiel whiskey": barter : 0, craft : 0},
    {"purified water": barter : 0, craft : 0},
    {"Portable defibrillator": barter : 0, craft : 0},
    {"CMS surgery kits": barter : 0, craft : 0},
    {"TerraGroup Labs access keycards": barter : 0, craft : 0},
    {"Reshala's Golden TT": barter : 0, craft : 0},
    {"Killa's helmet": barter : 0, craft : 0},
    {"Shturman's stash key": barter : 0, craft : 0},
    {"BOSS cap": barter : 0, craft : 0},
    {"Secure Flash drives": barter : 0, craft : 0},
    {"Old firesteel": barter : 0, craft : 0},
    {"Antique axe": barter : 0, craft : 0},
    {"Battered antique book": barter : 0, craft : 0},
    {"FireKlean gun lube": barter : 0, craft : 0},
    {"Golden rooster": barter : 0, craft : 0},
    {"Silver Badge": barter : 0, craft : 0},
    {"Deadlyslob's beard oil": barter : 0, craft : 0},
    {"Golden 1GPhone": barter : 0, craft : 0},
    {"Jar of DevilDog mayo": barter : 0, craft : 0},
    {"Can of sprats": barter : 0, craft : 0},
    {"Fake mustache": barter : 0, craft : 0},
    {"Kotton beanie": barter : 0, craft : 0},
    {"Can of Dr. Lupo's coffee beans": barter : 0, craft : 0},
    {"Pestily plague mask": barter : 0, craft : 0},
    {"Raven figurine": barter : 0, craft : 0},
    {"Shroud half-mask": barter : 0, craft : 0},
    {"Veritas guitar pick": barter : 0, craft : 0},
    {"42nd Signature Blend English Tea": barter : 0, craft : 0},
    {"Evasion armband": barter : 0, craft : 0},
    {"Smoke balaclava": barter : 0, craft : 0},
    {"Can of RatCola": barter : 0, craft : 0},
    {"Loot Lord plushie": barter : 0, craft : 0},
    {"WZ Wallet": barter : 0, craft : 0},
    {"LVNDMARK's rat poison": barter : 0, craft : 0},
    {"Secure container Epsilon": barter : 0, craft : 0},
};
