var csv = [[0, "Debut", "Elimination", "", ""],
[1, "Search mission", "Elimination", "", ""],
[2, "Checking", "Elimination", "", ""],
[3, "Shootout picnic", "Elimination", "", ""],
[4, "Delivery from the past", "Elimination", "", ""],
[5, "BP depot", "Elimination", "", ""],
[6, "The bunker - Part 1", "Elimination", "", ""],
[7, "The bunker - Part 2", "Elimination", "", ""],
[8, "Bad rep evidence", "Elimination", "", ""],
[9, "Ice cream cones", "Elimination", "", ""],
[10, "No place for renegades", "Elimination", "", ""],
[11, "Documents", "Elimination", "", ""],
[12, "Postman Pat - Part 1", "Elimination", "", ""],
[13, "Shaking up teller", "Elimination", "", ""],
[14, "The Punisher - Part 1", "Elimination", "", ""],
[15, "The Punisher - Part 2", "Elimination", "", ""],
[16, "The Punisher - Part 3", "Elimination", "", ""],
[17, "The Punisher - Part 4", "Elimination", "", ""],
[18, "The Punisher - Part 5", "Elimination", "", ""],
[19, "The Punisher - Part 6", "Elimination", "", ""],
[20, "Anesthesia", "Elimination", "", ""],
[21, "Grenadier", "Elimination", "", ""],
[22, "Insomnia", "Elimination", "", ""],
[23, "Test drive - Part 1", "Elimination", "", ""],
[24, "Perfect mediator", "Elimination", "", ""],
[25, "Polikhim hobo", "Elimination", "", ""],
[26, "Regulated materials", "Elimination", "", ""],
[27, "Big customer", "Elimination", "", ""],
[28, "No offence", "Elimination", "", ""],
[29, "Capturing Outposts", "Elimination", "", ""],
[30, "Intimidator", "Elimination", "", ""],
[31, "Escort", "Elimination", "", ""],
[32, "Shortage", "PickUp", "", ""],
[33, "Operation Aquarius - Part 1", "PickUp", "", ""],
[34, "Operation Aquarius - Part 2", "PickUp", "", ""],
[35, "Sanitary Standards - Part 1", "PickUp", "", ""],
[36, "Sanitary Standards - Part 2", "PickUp", "", ""],
[37, "Painkiller", "PickUp", "", ""],
[38, "Pharmacist", "PickUp", "", ""],
[39, "Car repair", "PickUp", "", ""],
[40, "Hippocratic Oath", "PickUp", "", ""],
[41, "Disease history", "PickUp", "", ""],
[42, "Supply plans", "PickUp", "", ""],
[43, "Health Care Privacy - Part 1", "PickUp", "", ""],
[44, "Health Care Privacy - Part 2", "PickUp", "", ""],
[45, "Health Care Privacy - Part 3", "PickUp", "", ""],
[46, "An Apple a day keeps the Doctor away", "PickUp", "", ""],
[47, "Health Care Privacy - Part 4", "PickUp", "", ""],
[48, "Athlete", "PickUp", "", ""],
[49, "Private clinic", "PickUp", "", ""],
[50, "Health Care Privacy - Part 5", "PickUp", "", ""],
[51, "Decontamination service", "PickUp", "", ""],
[52, "General wares", "PickUp", "", ""],
[53, "Colleagues - Part 1", "PickUp", "", ""],
[54, "Colleagues - Part 2", "PickUp", "", ""],
[55, "Colleagues - Part 3", "PickUp", "", ""],
[56, "Postman Pat - Part 2", "PickUp", "", ""],
[57, "Out of curiosity", "PickUp", "", ""],
[58, "Trust regain", "PickUp", "", ""],
[59, "Crisis", "PickUp", "", ""],
[60, "Seaside Vacation", "PickUp", "", ""],
[61, "Supplier", "PickUp", "", ""],
[62, "The Extortionist", "PickUp", "", ""],
[63, "Stirrup", "PickUp", "", ""],
[64, "What's on the flash drive?", "PickUp", "", ""],
[65, "Golden Swag", "PickUp", "", ""],
[66, "Chemical - Part 1", "PickUp", "", ""],
[67, "Chemical - Part 2", "PickUp", "", ""],
[68, "Chemical - Part 3", "PickUp", "", ""],
[69, "Chemical - Part 4", "PickUp", "", ""],
[70, "Loyalty buyout", "PickUp", "", ""],
[71, "Vitamins - Part 1", "PickUp", "", ""],
[72, "Vitamins - Part 2", "PickUp", "", ""],
[73, "Friend from the West - Part 1", "PickUp", "", ""],
[74, "Friend from the West - Part 2", "PickUp", "", ""],
[75, "Informed means armed", "PickUp", "", ""],
[76, "Chumming", "PickUp", "", ""],
[77, "Silent caliber", "PickUp", "", ""],
[78, "Bullshit", "PickUp", "", ""],
[79, "Setup", "PickUp", "", ""],
[80, "Flint", "PickUp", "", ""],
[81, "Lend lease - Part 1", "PickUp", "", ""],
[82, "Kind of sabotage", "PickUp", "", ""],
[83, "Rigged game", "PickUp", "", ""],
[84, "Safe corridor", "PickUp", "", ""],
[85, "Night Sweep", "PickUp", "", ""],
[86, "Fishing Gear", "Completion", "", ""],
[87, "Tigr Safari", "Completion", "", ""],
[88, "Scrap Metal", "Completion", "", ""],
[89, "Eagle Eye", "Completion", "", ""],
[90, "Humanitarian Supplies", "Completion", "", ""],
[91, "The Cult - Part 1", "Completion", "", ""],
[92, "The Cult - Part 2", "Completion", "", ""],
[93, "Spa Tour - Part 1", "Completion", "", ""],
[94, "Spa Tour - Part 2", "Completion", "", ""],
[95, "Spa Tour - Part 3", "Completion", "", ""],
[96, "Spa Tour - Part 4", "Completion", "", ""],
[97, "Spa Tour - Part 5", "Completion", "", ""],
[98, "Spa Tour - Part 6", "Completion", "", ""],
[99, "Spa Tour - Part 7", "Completion", "", ""],
[100, "Cargo X - Part 1", "Completion", "", ""],
[101, "Cargo X - Part 2", "Completion", "", ""],
[102, "Cargo X - Part 3", "Completion", "", ""],
[103, "Wet Job - Part 1", "Completion", "", ""],
[104, "Wet Job - Part 2", "Completion", "", ""],
[105, "Wet Job - Part 3", "Completion", "", ""],
[106, "Wet Job - Part 4", "Completion", "", ""],
[107, "Wet Job - Part 5", "Completion", "", ""],
[108, "Mentor", "Completion", "", ""],
[109, "Wet Job - Part 6", "Completion", "", ""],
[110, "The guide", "Completion", "", ""],
[111, "Samples", "Completion", "", ""],
[112, "TerraGroup employee", "Completion", "", ""],
[113, "Lend lease - Part 2", "Completion", "", ""],
[114, "Peacekeeping mission", "Completion", "", ""],
[115, "Classified technologies", "Completion", "", ""],
[116, "Revision", "Completion", "", ""],
[117, "Cleaner", "Completion", "", ""],
[118, "Special Equipment", "Completion", "", ""],
[119, "Introduction", "Completion", "", ""],
[120, "Gunsmith - Part 1", "Completion", "", ""],
[121, "Gunsmith - Part 2", "Completion", "", ""],
[122, "Gunsmith - Part 3", "Completion", "", ""],
[123, "Gunsmith - Part 4", "Completion", "", ""],
[124, "Gunsmith - Part 5", "Completion", "", ""],
[125, "Gunsmith - Part 6", "Completion", "", ""],
[126, "Gunsmith - Part 7", "Completion", "", ""],
[127, "Gunsmith - Part 8", "Completion", "", ""],
[128, "Gunsmith - Part 9", "Completion", "", ""],
[129, "Gunsmith - Part 10", "Completion", "", ""],
[130, "Gunsmith - Part 11", "Completion", "", ""],
[131, "Gunsmith - Part 12", "Completion", "", ""],
[132, "Gunsmith - Part 13", "Completion", "", ""],
[133, "Gunsmith - Part 14", "Completion", "", ""],
[134, "Gunsmith - Part 15", "Completion", "", ""],
[135, "Gunsmith - Part 16", "Completion", "", ""],
[136, "Signal - Part 1", "Completion", "", ""],
[137, "Insider", "Completion", "", ""],
[138, "Signal - Part 2", "Completion", "", ""],
[139, "Scout", "Completion", "", ""],
[140, "Surplus goods", "Completion", "", ""],
[141, "Back door", "Completion", "", ""],
[142, "Signal - Part 3", "Completion", "", ""],
[143, "Signal - Part 4", "Completion", "", ""],
[144, "Farming - Part 1", "Completion", "", ""],
[145, "Farming - Part 2", "Completion", "", ""],
[146, "Bad habit", "Completion", "", ""],
[147, "Farming - Part 3", "Completion", "", ""],
[148, "Farming - Part 4", "Completion", "", ""],
[149, "Psycho Sniper", "Completion", "", ""],
[150, "A Shooter Born in Heaven", "Completion", "", ""],
[151, "Fertilizers", "Completion", "", ""],
[152, "Import", "Completion", "", ""],
[153, "Chemistry closet", "Completion", "", ""],
[154, "Calibration", "Completion", "", ""],
[155, "The Courier", "Completion", "", ""],
[156, "Only business", "Merchant", "", ""],
[157, "Make ULTRA Great Again", "Merchant", "", ""],
[158, "Big sale", "Merchant", "", ""],
[159, "A fuel matter", "Merchant", "", ""],
[160, "Inventory check", "Merchant", "", ""],
[161, "The Blood of War - Part 1", "Merchant", "", ""],
[162, "Dressed to kill", "Merchant", "", ""],
[163, "Gratitude", "Merchant", "", ""],
[164, "Hot delivery", "Merchant", "", ""],
[165, "Scavenger", "Merchant", "", ""],
[166, "Sales Night", "Merchant", "", ""],
[167, "Database - Part 1", "Merchant", "", ""],
[168, "Database - Part 2", "Merchant", "", ""],
[169, "Minibus", "Merchant", "", ""],
[170, "Sew it good - Part 1", "Merchant", "", ""],
[171, "The Blood of War - Part 2", "Merchant", "", ""],
[172, "The Blood of War - Part 3", "Merchant", "", ""],
[173, "Living high is not a crime - Part 2", "Merchant", "", ""],
[174, "Sew it good - Part 2", "Merchant", "", ""],
[175, "The key to success", "Merchant", "", ""],
[176, "No fuss needed", "Merchant", "", ""],
[177, "The stylish one", "Merchant", "", ""],
[178, "Supervisor", "Merchant", "", ""],
[179, "Sew it good - Part 3", "Merchant", "", ""],
[180, "Living high is not a crime - Part 1", "Merchant", "", ""],
[181, "Sew it good - Part 4", "Merchant", "", ""],
[182, "Charisma brings success", "Merchant", "", ""],
[183, "Textile - Part 1", "Merchant", "", ""],
[184, "Textile - Part 2", "Merchant", "", ""],
[185, "Long Line", "Merchant", "", ""],
[186, "Booze", "Merchant", "", ""],
[187, "Acquaintance", "Completion", "", ""],
[188, "The survivalist path - Unprotected, but dangerous", "Completion", "", ""],
[189, "The survivalist path - Thrifty", "Completion", "", ""],
[190, "The survivalist path - Zhivchik", "Completion", "", ""],
[191, "The survivalist path - Wounded beast", "Completion", "", ""],
[192, "The survivalist path - Tough guy", "Completion", "", ""],
[193, "Courtesy visit", "Completion", "", ""],
[194, "Nostalgia", "Completion", "", ""],
[195, "The survivalist path - Cold blooded", "Completion", "", ""],
[196, "The survivalist path - Junkie", "Completion", "", ""],
[197, "The survivalist path - Eagle-owl", "Completion", "", ""],
[198, "The survivalist path - Combat medic", "Completion", "", ""],
[199, "Ambulance", "Completion", "", ""],
[200, "Huntsman path - Secured perimeter", "Completion", "", ""],
[201, "Reserve", "Completion", "", ""],
[202, "Huntsman path - Woods cleaning", "Completion", "", ""],
[203, "Huntsman path - Controller", "Completion", "", ""],
[204, "Huntsman path - Evil watchman", "Completion", "", ""],
[205, "Fishing place", "Completion", "", ""],
[206, "Huntsman path - The trophy", "Completion", "", ""],
[207, "Huntsman path - Justice", "Completion", "", ""],
[208, "Huntsman path - Sellout", "Completion", "", ""],
[209, "Huntsman path - Woods keeper", "Completion", "", ""],
[210, "Hunting trip", "Completion", "", ""],
[211, "Huntsman Path - Factory Chief", "Completion", "", ""],
[212, "Huntsman path - Eraser - Part 1", "Completion", "", ""],
[213, "Huntsman path - Eraser - Part 2", "Completion", "", ""],
[214, "The Tarkov shooter - Part 1", "Completion", "", ""],
[215, "The Tarkov shooter - Part 2", "Completion", "", ""],
[216, "The Tarkov shooter - Part 3", "Completion", "", ""],
[217, "The Tarkov shooter - Part 4", "Completion", "", ""],
[218, "The Tarkov shooter - Part 5", "Completion", "", ""],
[219, "The Tarkov shooter - Part 6", "Completion", "", ""],
[220, "The Tarkov shooter - Part 7", "Completion", "", ""],
[221, "The Tarkov shooter - Part 8", "Completion", "", ""],
[222, "Shady business", "Completion", "", ""],
[223, "Huntsman path - Sadist", "Completion", "", ""],
[224, "Hunter", "Completion", "", ""],
[225, "Pest control", "Completion", "", ""],
[226, "Swift One", "Completion", "", ""],
[227, "Huntsman Path - Relentless", "Completion", "", ""],
[228, "The Hermit", "Completion", "", ""],
[229, "Collector", "PickUp", "", ""],
[230, "The Choice", "PickUp", "", ""]];

